### ISSUE TITLE
Team 3 (Course Schedule)

### ISSUE THREAD

**Issue by caldwella2** [OS-Sketch/www.os-sketch.com#4]
Proactively decide what chapters to learn and choose two experts for the week for each chapter.

**Comment by gkapfham** [comment]
Hello @caldwella2, thanks for raising this issue, I appreciate it!

As you are planning which chapters to include for this semester, please make sure that you refer to this web site:

https://pages.cs.wisc.edu/~remzi/OSTEP/

It is also important for you to review the Fall 2022 academic calendar that will show you how much time we have:

https://sites.allegheny.edu/registrar/fall-2022-academic-calendar/

Please make sure that you do not assign readings or schedule a module during the Fall Break or Thanksgiving Break.

If you check the web site, you will see that I have already made some suggestions for modules and sub-modules. Please make sure that every module or sub-module has a two word name like "Systems Introduction". You then need to ensure that there is a key technical question that learners must be able to answer at the end of that module. You should also pick a fixed number of key technical terms (say 3 or 5 terms) and then state the term and give a definition of it.

I suggest that you start by first outlining the entire semester and picking the chapters that you want to cover. You should take care to ensure that when you pick a specific chapter you have covered the pre-req material for that chapter. It is also important to ensure that the course schedule follows a logical order that will not confuse the learners in the course. Finally, you should make sure to build in at least one or two weeks that are for the review of the material covered to date.

It is important for your team to collaborate with the teams that are respectively defining the learning objectives and the technical diagram of an operating system. Specifically, we want to make sure that there are learning objectives that connect to every chapter you are going to cover. It is also necessary for the technical diagram of an operating system to cover all of the key components that we are going to study this semester. This means that the diagram should not have "file system"  component if there is no content in the course schedule about file systems. Ultimately, everything in the diagram should be something that a person can learn about if they follow all of the content in the course schedule.

After you have finished creating a portion of the course schedule, make sure that you request and receive feedback from me and several other members of the course. We want to make sure that everyone agrees with the topic listing that you pick and the pace that you propose for our course.

**Comment by gkapfham** [comment]
Hello @caldwella2 and @Jordan-A and the course schedule team!

I see that you have already create a PR #9. What part of the content do you want us to review so far?

Also, I marked your PR as a WOP draft since it looks like it is not yet finished.

What is the timeline that you are hoping to follow when it comes to finishing the course schedule?

**Comment by DlHolland** [comment]
We'd like to add a table of contents to the top of the course schedule.  As experts add content to the schedule it will get longer and more difficult to navigate.  A table of contents that links the user to the specific week they want would be very helpful so people don't have to do as much scrolling.
