### ISSUE TITLE
[Feedback]: Compass and SASS should contain links

### ISSUE THREAD

**Issue by burgess01** [OS-Sketch/www.os-sketch.com#59]
### What is your feedback about the site?

My feedback about the site is that on the syllabus page there should be links to the compass and to Student Acessability and Support Services. Here are the links that I think should be added on these sections:

Compass: https://dspace.allegheny.edu/handle/10456/42164

SASS: https://sites.allegheny.edu/studentaccessibility/ 

It is key to note that these links should be hidden using the markdown functionality for adding a link to text like the other links are on the site.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Peter-Snipes** [comment]
The required links are now on the website.

**Comment by Peter-Snipes** [comment]
Take out extra words

**Comment by Peter-Snipes** [comment]
finished
